version: 1
services:
  - type: web
    name: budgetee
    env: static
    staticPublishPath: build
    buildCommand: npm run build
    startCommand: npm start
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
